artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.dropbox.com/scl/fi/b35ehzrj4fya0vn6hpwo9/dataset.zip?rlkey=mwlcftlrpx81h067antb11bpn&st=yy31yp2f&dl=1
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion